# Railway.toml - Configuration for Railway deployment
# This file optimizes container behavior for long-running novel generation

[build]
builder = "nixpacks"

[deploy]
# Increase health check timeout for longer operations
healthcheckTimeout = 300
# Increase deployment timeout for container startup
deploymentTimeout = 600
# Restart policy for container crashes
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Environment variables for Railway optimization
[env]
# Prevent Railway from putting container to sleep
RAILWAY_STATIC_URL = "true"
# Increase Node.js memory limit for large operations
NODE_OPTIONS = "--max-old-space-size=4096"
# Keep connections alive
RAILWAY_TCP_PROXY_PORT = "$PORT"

# Optional: Configure custom start command
[start]
cmd = "node index.js"

# Configure volume persistence (if needed for file storage)
# [volumes]
# data = "/app/data"
